"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var UserController_1 = require("../controllers/UserController");
var AuthController_1 = require("../controllers/AuthController");
var authMiddleware_1 = require("../middleware/authMiddleware");
var rolMiddleware_1 = require("../middleware/rolMiddleware");
var userRouter = (0, express_1.Router)();
userRouter.post("/register", AuthController_1.registerController);
userRouter.post("/login", AuthController_1.loginController);
userRouter.get("/users", authMiddleware_1.authMiddleware, (0, rolMiddleware_1.checkRol)(["admin"]), UserController_1.default.getUsers);
userRouter.get("/users/:id", authMiddleware_1.authMiddleware, (0, rolMiddleware_1.checkRol)(["admin"]), UserController_1.default.getUser);
userRouter.patch("/users/:id", authMiddleware_1.authMiddleware, (0, rolMiddleware_1.checkRol)(["admin"]), UserController_1.default.updateUser);
userRouter.delete("/users/:id", authMiddleware_1.authMiddleware, (0, rolMiddleware_1.checkRol)(["admin"]), UserController_1.default.deleteUser);
exports.default = userRouter;
